### ISSUE TITLE
Possible incompatibility with Datadog agent ( version 6 )

### ISSUE THREAD

**Issue by ericBidcom** [DataDog/php-datadogstatsd#57] opened 2018-03-07 13:37 UTC
Hi. I'm using this client and it's working fine with Datadog agent ( v5.22 ) but when I upgrade to  Datadog v6, the timing metrics doesnt work. 

More details:
PHP: 7.0
OS: Ubuntu 16

Thanks in advance!

**Comment by masci** [comment] 2018-03-09 13:18
Hi @ericBidcom and thanks for reporting.
Do you have a snippet of code we can use to reproduce the issue?

**Comment by ericBidcom** [comment] 2018-03-09 14:01
Hi @masci . I'm using two simple metrics:

```
...
   $statsd->increment('request.ok');
   $statsd->timing('request.time', microtime(true) - $start_time);
...
```
As I said, it works fine with Datadog v5.22 but when I upgrade to v6, it seems that client doesnt send the request.time metric. The dashboard only show the request.ok metric.

Let me know if you need more information
thanks!

**Comment by masci** [comment] 2018-03-10 12:30
This works for me with Agent 6.0.0:
```
↳ php -a
Interactive shell

php > require './src/DogStatsd.php';
php > $statsd = new DataDog\DogStatsd();
php > $statsd->timing("query.foo.time", 200);
php > $statsd->increment('page.foo.views');
```

Going to close this since the problem seems to be on the Agent side, maybe some configuration related issue. Can you reach out to support@datadoghq.com for further investigation?

**Closed by masci** 2018-03-10 12:30 UTC

**Comment by funkjedi** [comment] 2018-03-24 07:49
Same thing happened to me when I upgraded. I think there must be a bug somewhere in the code migrating the v5 config over to v6. Found the culprit inside `datadog.yaml`:

```yaml
histogram_aggregates: []
histogram_percentiles: []
```

After changing to the defaults:

```yaml
histogram_aggregates: ["max", "median", "avg", "count"]
histogram_percentiles: ["0.95"]
```

Everything started working again.
